services:
  journey-sync-ts:
    image: tailscale/tailscale:latest
    container_name: journey-sync-ts
    hostname: journey-sync
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      # - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - "TS_EXTRA_ARGS=--advertise-connector --advertise-tags=tag:container,tag:journey-app-connectors --reset"
      - TS_SERVE_CONFIG=/config/journey-sync.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      # - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - journey-ts-volume:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    network_mode: host
  journey-sync-self-hosted-service:
    image: journeycloud/journey-sync-self-hosted
    labels:
      kompose.volume.size: 4Gi
    environment:
      # EXPRESS_SERVER_PORT: 8080
      EXPRESS_SERVER_PORT: 80
      REDIS_PORT: 6379
      DISABLE_SSL: NO
      DOMAIN: ${JOURNEY_SYNC_DOMAIN}
      ROOT_MONGO_DB_URL: mongodb://${JOURNEY_SYNC_MONGO_ROOT_USERNAME}:${JOURNEY_SYNC_MONGO_ROOT_PASSWORD}@journey-mongodb-service:27017
      MONGO_DB_URL: mongodb://user:password@journey-mongodb-service:27017/journey
      REDIS_URL: redis://journey-redis-service:6379
      FS_PATH: /mnt/data
      SIGNED: ${JOURNEY_SYNC_SIGNED}
      ADMIN_JS_COOKIE_PASSWORD: ${JOURNEY_SYNC_ADMIN_JS_COOKIE_PASSWORD}
      TYPESENSE_HOST: journey-typesense-service
      TYPESENSE_PORT: 8108
      TYPESENSE_PROTOCOL: http
      TYPESENSE_API_KEY: ${JOURNEY_SYNC_TYPESENSE_API_KEY}
    entrypoint: 'npm run launch'
    depends_on:
      - journey-sync-ts
      - journey-mongodb-service
      - journey-redis-service
      - journey-typesense-service
    volumes:
      - journey-fs-volume:/mnt/data
    ports:
    #   - 8080:8080
      - 80:80
    networks:
      - internal
  journey-sync-self-hosted-media:
    image: journeycloud/journey-sync-self-hosted
    labels:
      kompose.volume.size: 4Gi
    environment:
      REDIS_PORT: 6379
      DISABLE_SSL: NO
      DOMAIN: ${JOURNEY_SYNC_DOMAIN}
      ROOT_MONGO_DB_URL: mongodb://${JOURNEY_SYNC_MONGO_ROOT_USERNAME}:${JOURNEY_SYNC_MONGO_ROOT_PASSWORD}@journey-mongodb-service:27017
      MONGO_DB_URL: mongodb://user:password@journey-mongodb-service:27017/journey
      REDIS_URL: redis://journey-redis-service:6379
      FS_PATH: /mnt/data
    entrypoint: 'npm run launchMedia'
    depends_on:
      - journey-sync-ts
      - journey-sync-self-hosted-service
    volumes:
      - journey-fs-volume:/mnt/data
    networks:
      - internal
  journey-mongodb-service:
    image: mongo:7.0
    labels:
      kompose.volume.size: 4Gi
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${JOURNEY_SYNC_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${JOURNEY_SYNC_MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: journey
    depends_on:
      - journey-sync-ts
    volumes:
      - journey-mongodb-volume:/data/db
    networks:
      - internal
  journey-redis-service:
    image: redis:7.2.4-alpine
    labels:
      kompose.volume.size: 4Gi
    depends_on:
      - journey-sync-ts
    volumes:
      - journey-redis-volume:/data
    command: redis-server
    networks:
      - internal
  journey-typesense-service:
    image: typesense/typesense:26.0
    labels:
      kompose.volume.size: 10Gi
    depends_on:
      - journey-sync-ts
    volumes:
      - journey-typesense-volume:/data
    command: '--data-dir /data --api-key=${JOURNEY_SYNC_TYPESENSE_API_KEY} --enable-cors'
    networks:
      - internal

volumes:
  journey-ts-volume:
      driver: local
  journey-mongodb-volume:
    labels:
      kompose.volume.size: 10Gi
  journey-typesense-volume:
    labels:
      kompose.volume.size: 10Gi
  journey-fs-volume:
    labels:
      kompose.volume.size: 20Gi
  journey-redis-volume:
    labels:
      kompose.volume.size: 4Gi

networks:
  internal:
    driver: bridge