services:
  linkwarden-postgres:
    image: postgres:16-alpine
    container_name: linkwarden_postgres
    restart: always
    env_file: .env
    volumes:
      - ${LINKWARDEN_DB_LOCATION}:/var/lib/postgresql/data
    networks:
      - linkwarden-network

  linkwarden-server:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden_server
    restart: always
    depends_on:
      - linkwarden-postgres
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@linkwarden-postgres:5432/postgres
    volumes:
      - ${LINKWARDEN_DATA_LOCATION}:/data/data
    networks:
      - linkwarden-network
      - proxy-bridge

networks:
  linkwarden-network:
    name: linkwarden_default
    external: false

  proxy-bridge:
    name: proxy_bridge
    external: true
